//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicAppointment
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public int TimeSlotId { get; set; }
    
        public virtual patient patient { get; set; }
        public virtual timeslot timeslot { get; set; }
    }
}
