//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicAppointment
{
    using System;
    using System.Collections.Generic;
    
    public partial class availability
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public availability()
        {
            this.timeslots = new HashSet<timeslot>();
        }
    
        public int Id { get; set; }
        public int DoctorId { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime AvailableFrom { get; set; }
        public System.DateTime AvailableTo { get; set; }
        public Nullable<int> AppointmentDuration { get; set; }
    
        public virtual doctor doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timeslot> timeslots { get; set; }
    }
}
